"""Builds WordOfWarcraft/Words.lua from the curated lists in tools/data/.

    pip install wordfreq
    python tools/build_words.py

Inputs:
  tools/data/answers.txt       hand-curated answers, `WORD  # note` per line
  tools/data/lore_guesses.txt  extra Warcraft words accepted as guesses but never answers
  tools/data/blocklist.txt     words never accepted, even as guesses
  wordfreq                     English 5-letter words with Zipf frequency >= MIN_ZIPF become valid guesses
                               (wordfreq data: CC BY-SA 4.0, https://github.com/rspeer/wordfreq)

ns.ANSWERS in Words.lua is in DAILY ORDER and APPEND-ONLY: puzzle n is ANSWERS[n] on every client version that
has at least n words. So this script keeps the existing order, drops nothing, and appends new answers from
answers.txt in a shuffled (fixed seed) order. Removing or replacing an answer that's already in Words.lua must be
done by hand (replace it in place, and only if its day hasn't come yet).
"""
import os
import random
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")
OUT = os.path.join(HERE, "..", "WordOfWarcraft", "Words.lua")
LENGTH = 5
MIN_ZIPF = 2.0
SEED = 20260928


def read_words(name):
    path = os.path.join(DATA, name)
    if not os.path.exists(path):
        return []
    words = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            word = line.split("#", 1)[0].strip().upper()
            if word:
                words.append(word)
    return words


def existing_order():
    if not os.path.exists(OUT):
        return []
    with open(OUT, encoding="utf-8") as fh:
        src = fh.read()
    m = re.search(r"ns\.ANSWERS = \{(.*?)\n\}", src, re.S)
    return re.findall(r'"([A-Z]+)"', m.group(1)) if m else []


def english_words():
    from wordfreq import top_n_list, zipf_frequency
    out = set()
    for w in top_n_list("en", 300000):
        # Runs of 3+ identical letters are interjections/noise (AAAAA, AAAHH), not words.
        if (len(w) == LENGTH and w.isascii() and w.isalpha() and not re.search(r"(.)\1\1", w)
                and zipf_frequency(w, "en") >= MIN_ZIPF):
            out.add(w.upper())
    return out


def build():
    answers = read_words("answers.txt")
    lore = read_words("lore_guesses.txt")
    blocked = set(read_words("blocklist.txt"))
    problems = [w for w in answers + lore if len(w) != LENGTH or not w.isalpha() or not w.isascii()]
    if problems:
        sys.exit("not %d letters A-Z: %s" % (LENGTH, problems))
    dupes = sorted({w for w in answers if answers.count(w) > 1})
    if dupes:
        sys.exit("duplicate answers: %s" % dupes)
    if blocked & set(answers):
        sys.exit("blocklisted answers: %s" % sorted(blocked & set(answers)))

    order = existing_order()
    missing = [w for w in order if w not in answers]
    if missing:
        sys.exit("answers already in Words.lua are missing from answers.txt (the list is append-only; "
                 "replace them in Words.lua by hand if their day hasn't come): %s" % missing)
    new = sorted(set(answers) - set(order))
    random.Random(SEED + len(order)).shuffle(new)
    order += new

    guesses = (english_words() | set(lore)) - blocked - set(order)
    write(order, sorted(guesses))
    print("answers: %d (%d new), extra guesses: %d" % (len(order), len(new), len(guesses)))


def write(order, guesses):
    lines = [
        "-- GENERATED by tools/build_words.py from tools/data/. Don't edit by hand, except to replace an answer",
        "-- in place (see build_words.py). ANSWERS is in daily order (puzzle n = ANSWERS[n]) and append-only.",
        "-- Guess list: English words from wordfreq (CC BY-SA 4.0, https://github.com/rspeer/wordfreq) plus Warcraft",
        "-- words.",
        "",
        "local _, ns = ...",
        "",
        "ns.ANSWERS = {",
    ]
    for i in range(0, len(order), 12):
        lines.append("    " + " ".join('"%s",' % w for w in order[i:i + 12]))
    lines.append("}")
    lines.append("")
    lines.append("-- Valid guesses besides the answers, space-separated (parsed on first use).")
    lines.append("ns.GUESSES = [[")
    for i in range(0, len(guesses), 16):
        lines.append(" ".join(guesses[i:i + 16]))
    lines.append("]]")
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    build()
